version: '3.7'

services:
  php-apache:
    build:
      context: ./php
    container_name: vulnerable-php-site
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    container_name: vulnerable-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  sync-server:
    build:
      context: ./sync
    container_name: sync-server
    volumes:
      - ./sync/data:/sync-data
    depends_on:
      - php-apache
    entrypoint: /bin/bash -c "while true; do rsync -avz /sync-data/ root@vulnerable-php-site:/var/www/html; sleep 1; done"
